TS_SEARCH_PATHS=(~/code/work ~/code/personal)
TS_EXTRA_SEARCH_PATHS=(
  ~/dotfiles:0
  ~/Dropbox/Notes:0
  ~/mhc:0
  ~/mhc/systems:1
)
TS_SESSION_COMMANDS=(
  "opencode"          # 0 - Opencode
  "nvim -c \"Neogit\"" # 1 - git UI
)
