services:

  dev:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/home/user/dotfiles'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
