- name: Set git credentials helper
  community.general.git_config:
    name: credential.helper
    value: osxkeychain
    scope: global
  when: ansible_distribution == "MacOSX"
  tags:
    - settings
    - git

- name: Set git credentials helper in Linux
  community.general.git_config:
    name: credential.helper
    value: store
    scope: global
  when: ansible_distribution == "Ubuntu"
  tags:
    - settings
    - git
