- name: Kill affected applications
  shell: for app in Safari Finder Dock Mail SystemUIServer; do killall "$app" >/dev/null 2>&1; done
  changed_when: false
  tags:
    - settings
    - mac
    - osx


- name: show the ~/Library folder in Finder
  command: chflags nohidden ~/Library
  changed_when: false
  tags:
    - settings
    - mac
    - osx

- name: "Finder: show all filename extensions"
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool 
    value: true
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - settings
    - mac
    - osx

- name: "Finder: show hidden files by default"
  community.general.osx_defaults:
    domain: com.apple.Finder 
    key: AppleShowAllFiles 
    type: bool 
    value: false
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - settings
    - mac
    - osx

- name: "Save window: expand save dialog by default"
  community.general.osx_defaults:
    domain: NSGlobalDomain 
    key: NSNavPanelExpandedStateForSaveMode 
    type: bool
    value: true
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - settings
    - mac
    - osx

- name: "Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)"
  community.general.osx_defaults:
    domain: NSGlobalDomain 
    key: AppleKeyboardUIMode 
    type: int
    value: 3
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - settings
    - mac
    - osx

- name: "Enable subpixel font rendering on non-Apple LCDs"
  community.general.osx_defaults:
    domain: NSGlobalDomain 
    key: AppleFontSmoothing 
    type: int
    value: 2
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - settings
    - mac
    - osx

- name: "Use current directory as default search scope in Finder"
  community.general.osx_defaults:
    domain: com.apple.finder 
    key: FXDefaultSearchScope 
    type: string
    value: "SCcf"
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - settings
    - mac
    - osx

- name: "Show Path bar in Finder"
  community.general.osx_defaults:
    domain: com.apple.finder 
    key: ShowPathbar 
    type: bool
    value: true
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - settings
    - mac
    - osx

- name: "Show Status bar in Finder"
  community.general.osx_defaults:
    domain: com.apple.finder 
    key: ShowStatusBar 
    type: bool
    value: true
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - settings
    - mac
    - osx

- name: "Disable press-and-hold for keys in favor of key repeat"
  community.general.osx_defaults:
    domain: NSGlobalDomain 
    key: ApplePressAndHoldEnabled 
    type: bool
    value: false
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - settings
    - mac
    - osx

- name: "Set a blazingly fast keyboard repeat rate"
  community.general.osx_defaults:
    domain: NSGlobalDomain 
    key: KeyRepeat
    type: int
    value: 1
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - settings
    - mac
    - osx

- name: "Set a shorter Delay until key repeat"
  community.general.osx_defaults:
    domain: InitialKeyRepeat
    key: KeyRepeat
    type: int
    value: 15
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - settings
    - mac
    - osx

- name: "Enable Safari’s debug menu"
  community.general.osx_defaults:
    domain: com.apple.Safari 
    key: IncludeInternalDebugMenu
    type: bool
    value: true
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - settings
    - mac
    - osx

- name: "Disable desktop icons"
  community.general.osx_defaults:
    domain: com.apple.finder 
    key: CreateDesktop
    type: string # Weird that this is a string but that's how it should be
    value: false
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - settings
    - mac
    - osx

















































