- name: Get zsh path
  command: which zsh
  changed_when: false
  register: zsh_path
  tags:
    - settings
    - shell

- name: Change user shell to zsh 
  become: yes
  user: name={{the_user}} shell={{ zsh_path.stdout }}
  tags:
    - settings
    - shell
