#!/usr/bin/env bash

hydrate() {
    if [ -f $2/.tmux_sessionizer ]; then
        tmux send-keys -t $1 "source $2/.tmux_sessionizer" c-M
    elif [ -f $HOME/.tmux_sessionizer ]; then
        tmux send-keys -t $1 "source $HOME/.tmux_sessionizer" c-M
    fi
}

if [[ $# -eq 1 ]]; then
  selected=$1
else
  static=$(find ~/Dropbox/Notes ~/dotfiles -mindepth 0 -maxdepth 0 -type d)
  dynamic=$(find ~/code/personal ~/code/work -mindepth 1 -maxdepth 1 -type d)
  selected=$(printf "${dynamic}\n${static}" | fzf)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

echo $selected

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  hydrate $selected_name $selected
  exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
  tmux new-session -ds $selected_name -c $selected
  hydrate $selected_name $selected
fi

tmux switch-client -t $selected_name
