## nom RSS reader config
## https://github.com/guyfedwards/nom

pager: internal
ordering: desc
showread: true
autoread: false

feeds:
  - url: https://us13.campaign-archive.com/feed?u=32cd932058e988b44c838f7bc&id=fca295a96e
  - url: https://tigerbeetle.com/blog/atom.xml
    name: TigerBeetle
  - url: https://matklad.github.io/feed.xml
    name: matklad
  - url: https://daverupert.com/atom.xml
    name: Dave Rupert
  - url: https://glfmn.io/rss.xml
    name: glfmn
  - url: https://piccalil.li/feed.xml
    name: Piccalilli
